---
# vars file for homebrew
cask_list:
  - iterm2
  - lastpass
  - clipy
  - shiftit
  - qqmusic
  - visual-studio-code
  - zoom
  - docker
  - intellij-idea
  - sogouinput
  - postman
  - dbeaver-community

cli_list:
  - warrensbox/tap/tfswitch
  - jenv
  - nvm
  - autojump
  - kubectl
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - git-gui
  - watch
  - wget
  - graphviz
  - tmpwatch
  - jq
  - yq
  - tmux

# the value should pass from --extra-vars
sudo_password: ''
