---
# vars file for homebrew
cask_list:
  - iterm2
  - clipy
  - shiftit

cli_list:
  - warrensbox/tap/tfswitch
  - jenv
  - nvm
  - autojump
  - kubectl
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - git-gui
  - watch
  - wget
  - graphviz
  - tmpwatch
  - jq
  - yq
  - tmux
  - go
  - k9s
  - tree
  - expect
  - zsh
  - openjdk@8
  - openjdk
  - colima
  - docker
  - docker-compose
  - gnu-sed

# the value should pass from --extra-vars
sudo_password: ''
