---
# vars file for homebrew
cask_list:
  - iterm2
  - lastpass
  - clipy
  - shiftit
  - eudic
  - qqmusic
  - visual-studio-code
  - zoom
  - docker
  - intellij-idea

cli_list:
  - warrensbox/tap/tfswitch
  - jenv
  - nvm
  - autojump
  - zsh-autosuggestions
  - kubectl

# the value should pass from --extra-vars
sudo_password: ''